(function() {
    const i18nMap = {
        "+ Add": "+ 添加",
        "100.0% of the customization budget is available.": "自定义配额剩余 100.0% 可用。",
        "Account": "账户",
        "Accent": "强调色",
        "Action": "触发动作",
        "Actuation Permissions": "操作权限",
        "Add": "添加",
        "Add Folder": "添加文件夹",
        "Add MCP +": "添加 MCP +",
        "Add MCP Servers": "添加 MCP 服务器",
        "Agent Behavior": "智能体行为模式",
        "Agent Context & Capabilities": "智能体上下文与可用能力",
        "Agent Settings": "智能体设置",
        "Agent settings and permissions for conversations outside of projects.": "项目外对话的智能体设置和权限。",
        "Agent State": "智能体运行状态",
        "Agent is running a terminal command": "智能体正在运行终端命令...",
        "Airweave": "Airweave",
        "Airweave lets agents search any app.": "Airweave 让智能体可以搜索任何应用。",
        "Allow": "允许",
        "Allow Antigravity to read and write to your workspace files.": "允许 Antigravity 读取和写入您的工作区文件。",
        "Allow Antigravity to run commands in your local terminal.": "允许 Antigravity 在您的本地终端中运行指令。",
        "Allow full browser script execution without prompting.": "允许完整浏览器脚本执行，无需提示。",
        "Allow Tool Categories": "允许调用的工具类别",
        "Allow/deny agent browser actuation access to specific URLs.": "允许/拒绝智能体对特定 URL 的浏览器操作访问权限。",
        "AlloyDB for PostgreSQL": "AlloyDB for PostgreSQL",
        "AlloyDB for PostgreSQL Admin": "AlloyDB for PostgreSQL 管理",
        "AlloyDB for PostgreSQL Admin MCP Server enables AI assistants to interact with AlloyDB for PostgreSQL resources, including creating clusters and administering...": "AlloyDB for PostgreSQL 管理 MCP 服务器使 AI 助手能够与 AlloyDB for PostgreSQL 资源进行交互，包括创建集群和管理...",
        "Always Ask": "始终询问",
        "Always Proceed": "始终继续",
        "Android": "Android",
        "Android Management API": "Android 管理 API",
        "Access enterprise mobility data using natural language queries about device fleets, automated auditing of policy compliance, and the integration of device...": "关于设备集群使用自然语言查询来访问企业移动数据、自动审计策略合规性以及设备集成的功能...",
        "Antigravity": "Antigravity",
        "App": "应用设置",
        "App Settings": "应用设置",
        "Appearance": "外观",
        "Apply Code Patch": "应用此代码补丁",
        "Apply to Editor": "应用到代码编辑器",
        "ArizeTracingAssistant": "Arize 追踪助手",
        "This MCP server provides your LLM with docs and examples to instrument your AI apps with Arize AX. It also provides access to Arize support. Connect it to your IDE...": "此 MCP 服务器为您的 LLM 提供文档和示例，以便使用 Arize AX 装备您的 AI 应用。它还提供了访问 Arize 支持的功能。将其连接到您的 IDE...",
        "Artifact Review Policy": "产物审核策略",
        "Ask anything, @ to mention, / for actions": "问任何问题，输入 @ 提及，/ 触发动作",
        "Ask me": "每次询问我",
        "Atlassian": "Atlassian",
        "Atlassian MCP Server for interacting with Atlassian products.": "用于与 Atlassian 产品交互的 Atlassian MCP 服务器。",
        "Attach file": "添加附件 / 代码文件",
        "Attached Artifacts": "已挂载的代码生成物/组件",
        "Authentication Token Expiry": "身份验证令牌有效期",
        "Auto-Save": "自动保存会话",
        "Automatically save chats to history.": "在关闭或切换窗口时自动将聊天记录保存到历史列表中。",
        "Background": "后台运行",
        "Balanced": "平衡模式",
        "BigQuery": "BigQuery",
        "Interact with your BigQuery data using natural language. This MCP server allows you to securely connect to your datasets to search the datasets, inspect table...": "使用自然语言与您的 BigQuery 数据进行交互。此 MCP 服务器允许您安全地连接到您的数据集以搜索数据集、检查数据表...",
        "Block all browser JavaScript execution.": "阻止所有浏览器 JavaScript 执行。",
        "Browser": "浏览器设置",
        "Browser Actuation Permissions": "浏览器操作权限",
        "Browser Actuation Rules": "浏览器操作规则",
        "Browser Javascript Execution Policy": "浏览器 JavaScript 执行策略",
        "Browser Settings": "浏览器设置",
        "Build With Google Plugins": "构建与谷歌插件",
        "Build with Antigravity Plugins": "使用 Antigravity 插件构建",
        "By using this app, you agree to its Terms of Service": "使用本应用即表示您同意其服务条款",
        "Check for Updates": "检查更新",
        "Chrome DevTools": "Chrome DevTools",
        "Chrome DevTools MCP": "Chrome DevTools MCP",
        "Enable Antigravity to control and inspect a live Chrome browser, with access to the full power of Chrome DevTools for reliable automation, in-depth debugging, and...": "使 Antigravity 能够控制和检查正在运行的 Chrome 浏览器，并能使用完整的 Chrome DevTools 功能来实现可靠的自动化、深入的调试、以及...",
        "Choose how Antigravity looks on your device.": "选择 Antigravity 在您设备上的显示外观。",
        "Choose a predefined security preset for the agent. This controls terminal auto-execution policy, and file access policy.": "为智能体选择一个预定义的安全预设。这将控制终端自动执行策略和文件访问策略。",
        "Clear All History": "清除所有历史记录",
        "Clear Cache": "清除缓存",
        "Clear Console Logs": "清空控制台日志",
        "ClickHouse": "ClickHouse",
        "The ClickHouse MCP server enables agents to securely interact with ClickHouse databases. It provides a universal interface to execute SQL, explore data, and view...": "ClickHouse MCP 服务器使智能体能够安全地与 ClickHouse 数据库进行交互。它提供了一个执行 SQL、探索数据和查看的通用接口...",
        "Close": "关闭",
        "Close Tab": "关闭标签页",
        "Cloud Code Functions": "云端代码函数/服务对接",
        "Cloud Provider Endpoint": "云端服务接入端点",
        "Cloud Run": "Cloud Run",
        "Enable Antigravity to deploy apps to Google Cloud Run.": "允许 Antigravity 将应用部署到 Google Cloud Run。",
        "Cloud SQL for MySQL": "Cloud SQL for MySQL",
        "Interact with your Cloud SQL for MySQL data using natural language. This MCP server allows you to securely connect to your database for executing SQL queries,...": "使用自然语言与您的 Cloud SQL for MySQL 数据进行交互。此 MCP 服务器允许您安全地连接到您的数据库以执行 SQL 查询...",
        "Cloud SQL for MySQL Admin": "Cloud SQL for MySQL 管理",
        "Cloud SQL for MySQL Admin MCP Server enables AI assistants to interact with Cloud SQL for MySQL resources, including creating instances, administering users,...": "Cloud SQL for MySQL 管理 MCP 服务器使 AI 助手能够与 Cloud SQL for MySQL 资源进行交互，包括创建实例、管理用户、...",
        "Cloud SQL for PostgreSQL": "Cloud SQL for PostgreSQL",
        "Interact with your Cloud SQL for PostgreSQL data using natural language. This MCP server allows you to securely connect to your database for executing SQL queries,...": "使用自然语言与您的 Cloud SQL for PostgreSQL 数据进行交互。此 MCP 服务器允许您安全地连接到您的数据库以执行 SQL 查询...",
        "Cloud SQL for PostgreSQL Admin": "Cloud SQL for PostgreSQL 管理",
        "Cloud SQL for PostgreSQL Admin MCP Server enables AI assistants to interact with Cloud SQL for PostgreSQL resources, including creating instances, administering...": "Cloud SQL for PostgreSQL 管理 MCP 服务器使 AI 助手能够与 Cloud SQL for PostgreSQL 资源进行交互，包括创建实例、管理...",
        "Cloud SQL for SQL Server": "Cloud SQL for SQL Server",
        "Interact with your Cloud SQL for SQL Server data using natural language. This MCP server allows you to securely connect to your database for executing SQL queries,...": "使用自然语言与您的 Cloud SQL for SQL Server 数据进行交互。此 MCP 服务器允许您安全地连接到您的数据库以执行 SQL 查询...",
        "Cloud SQL for SQL Server Admin": "Cloud SQL for SQL Server 管理",
        "Cloud SQL for SQL Server Admin MCP Server enables AI assistants to interact with Cloud SQL for SQL Server resources, including creating instances, administering...": "Cloud SQL for SQL Server 管理 MCP 服务器使 AI 助手能够与 Cloud SQL for SQL Server 资源进行交互，包括创建实例、管理...",
        "Cloud SQL Managed MCP": "Cloud SQL 托管式 MCP",
        "The Cloud SQL remote MCP server lets you access and run Cloud SQL tools to create, manage, and query Cloud SQL resources from your AI-enabled developme...": "Cloud SQL 远程 MCP 服务器允许您访问和运行 Cloud SQL 工具，以便从您的 AI 驱动开发环境中创建、管理和查询 Cloud SQL 资源...",
        "Cloud Synchronization": "云端同步",
        "Cloud Sync": "云端同步",
        "Command Execution": "终端命令执行控制",
        "Command Palette": "命令面板",
        "Commands Outside Sandbox": "沙箱外命令",
        "Completion tokens": "输出（生成）Token",
        "Configure AI models and view your quota.": "配置 AI 模型并查看您的配额。",
        "Configure allowed and denied paths for file reads and writes.": "配置允许和拒绝的文件读写路径。",
        "Configure allowed and denied URLs for browser actuation.": "配置允许和拒绝用于浏览器操作的 URL。",
        "Configure allowed and denied URLs for reading.": "配置允许和拒绝的读取网址 (URL)。",
        "Configure allowed commands outside the sandbox.": "配置沙箱外允许的终端命令。",
        "Configure allowed terminal commands.": "配置允许的终端命令。",
        "Configure custom agent behavior, prompts, and tools.": "配置自定义智能体（Agent）的行为模式、提示词及工具链。",
        "Configure default behaviors, skills, and MCP servers.": "配置默认行为、技能和 MCP 服务器。",
        "Configure external tools via Model Context Protocol.": "通过模型上下文协议 (MCP) 配置外部工具。",
        "Configure global allowed and denied resource permissions. Learn more.": "配置全局允许和拒绝的资源权限。了解更多。",
        "Configure the agent's visual theme and display preferences.": "配置智能体的视觉主题和显示偏好。",
        "Configure the browser subagent. It requires Google Chrome to be installed. The browser subagent can be invoked by typing /browser in the conversation input box.": "配置浏览器子智能体。这需要安装 Google Chrome。可以通过在对话输入框中输入 /browser 来调用浏览器子智能体。",
        "Configures how the agent tries to access files outside of its working folders.": "配置智能体如何尝试访问其工作文件夹外部的文件。",
        "Context Capacity Status": "上下文容量状态",
        "Context Truncation Strategy": "上下文截断策略",
        "Context Window Allocation": "上下文窗口(记忆)分配",
        "Controls whether terminal commands require your approval before running.": "控制终端命令在运行前是否需要您的批准。",
        "Controls whether the agent can run custom JavaScript to automate complex browser actions.": "控制智能体是否能够运行自定义 JavaScript 以自动化复杂的浏览器操作。",
        "Conversation History": "历史对话",
        "Conversations": "对话管理",
        "Copy code": "复制代码",
        "Core tools and knowledge required to develop for Android": "为 Android 开发所需的核心工具和知识。",
        "Create Project": "创建项目",
        "Creative": "富有创意",
        "Curated collection of agent skills for science.": "为科学场景精心策划的智能体技能集合。",
        "Custom": "自定义",
        "Custom Instructions": "自定义指令 / 角色设定",
        "Custom Proxy": "自定义代理服务器",
        "Customize": "自定义",
        "Dart": "Dart",
        "The Dart and Flutter MCP server exposes Dart (and Flutter) development tool actions to compatible AI-assistant clients.": "Dart 和 Flutter MCP 服务器向兼容的 AI 助手客户端暴露 Dart（和 Flutter）开发工具操作。",
        "Dark": "深色模式",
        "Dark Theme": "深色主题",
        "Default": "默认",
        "Default Dark": "默认深色",
        "Default Light": "默认浅色",
        "Delete all local browser data and cookies.": "删除所有本地浏览器数据、历史记录和 Cookie。",
        "Deny": "拒绝",
        "Direct": "直连模式 (不使用代理)",
        "Disabled": "禁用",
        "Discard Changes": "放弃本次更改",
        "Download": "下载",
        "Edit": "编辑",
        "Email": "电子邮箱",
        "Enable Antigravity to control and inspect a live Chrome browser, with access to the full power of Chrome DevTools for reliable automation, in-depth debugging, and...": "使 Antigravity 能够控制和检查正在运行的 Chrome 浏览器，并能使用完整的 Chrome DevTools 功能来实现可靠的自动化、深入的调试、以及...",
        "Enable Antigravity to deploy apps to Google Cloud Run.": "允许 Antigravity 将应用部署到 Google Cloud Run。",
        "Enable Antigravity to interact with Google Kubernetes Engine (GKE).": "允许 Antigravity 与 Google Kubernetes Engine (GKE) 交互。",
        "Enable Telemetry": "允许发送诊断数据",
        "Enable Workspace Auto-Sync": "启用工作区自动同步",
        "Executing...": "正在执行指令...",
        "Execution Safety Boundary": "执行安全边界",
        "Execute URLs": "执行 URL",
        "Fast": "快速",
        "Figma Dev Mode MCP": "Figma 开发者模式 MCP",
        "Figma Developer Mode MCP": "Figma 开发者模式 MCP",
        "The Dev Mode MCP Server brings Figma directly into your workflow by providing important design information and context to AI agents generating code from Fig...": "开发模式 MCP 服务器通过向从 Figma 生成代码的 AI 智能体提供重要的设计信息和上下文，将 Figma 直接带入您的工作流程...",
        "File": "文件",
        "File Access Rules": "文件访问规则",
        "File Permissions": "文件权限",
        "File Picker": "文件选择器",
        "File System": "文件系统访问",
        "Firebase": "Firebase",
        "Prototype, build & run modern apps users love with Firebase's backend, AI, and operational infrastructure.": "利用 Firebase 的后端、AI 和运营基础设施，原型设计、构建和运行用户喜爱的现代应用。",
        "The Firebase Model Context Protocol (MCP) Server gives AI-powered development tools the ability to work with your Firebase projects and your app's codebase.": "Firebase 模型上下文协议 (MCP) 服务器使 AI 驱动的开发工具能够操作您的 Firebase 项目和应用的代码库。",
        "Focus Input": "聚焦到输入框",
        "Foreground": "前景色",
        "Full Machine": "完全机器权限",
        "General": "通用",
        "Generated Suggestions": "AI 推荐的下一步操作",
        "Genkit": "Genkit",
        "The Genkit Model Context Protocol (MCP) Server gives AI-powered development tools the ability to build, debug and inspect your Genkit app.": "Genkit 模型上下文协议 (MCP) 服务器使 AI 驱动的开发工具能够构建、调试和检查您的 Genkit 应用。",
        "GitHub": "GitHub",
        "The GitHub MCP Server is a Model Context Protocol (MCP) server that provides seamless integration with GitHub APIs, enabling advanced automation and...": "GitHub MCP 服务器是一个模型上下文协议 (MCP) 服务器，它提供了与 GitHub API 的无缝集成，从而实现了高级自动化和...",
        "Go Back": "后退",
        "Go Forward": "前进",
        "Go to Projects": "前往项目",
        "Google Antigravity SDK": "Google Antigravity SDK",
        "Using the Antigravity Python SDK to build AI agents": "使用 Antigravity Python SDK 构建 AI 智能体。",
        "Google Cloud Bigtable Admin": "Google Cloud Bigtable 管理",
        "The Bigtable Admin remote MCP server lets you manage Bigtable resources.": "Bigtable Admin 远程 MCP 服务器让您可以管理 Bigtable 资源。",
        "Google Cloud Firestore": "Google Cloud Firestore",
        "Interact with documents stored in a Firestore database using natural language.": "使用自然语言与存储在 Firestore 数据库中的文档进行交互。",
        "Google Cloud Logging": "Google Cloud 日志",
        "Access resources in the Cloud Logging platform using natural language.": "使用自然语言访问 Cloud Logging 平台中的资源。",
        "Google Cloud Monitoring": "Google Cloud 监控",
        "Access resources in the Cloud Monitoring platform using natural language.": "使用自然语言访问 Cloud Monitoring 平台中的资源。",
        "Google Cloud Pub/Sub": "Google Cloud Pub/Sub",
        "Manage Pub/Sub resources and publish messages. Create, list, get, update, and delete Pub/Sub topics, subscriptions, and snapshots, as well as publish messages t...": "管理 Pub/Sub 资源并发布消息。创建、罗列、获取、更新和删除 Pub/Sub 主题、订阅和快照，以及向其发布消息...",
        "Google Cloud Resource Manager": "Google Cloud 资源管理器",
        "Google Compute Engine": "Google Compute Engine",
        "Perform a range of infrastructure management tasks, including: manage virtual machine (VM) instances, manage instance group managers and instance template...": "执行一系列基础设施管理任务，包括：管理虚拟机 (VM) 实例、管理实例组管理器和实例模板...",
        "Google Developer Knowledge": "Google 开发者知识",
        "The Google Developer Knowledge MCP server gives AI-powered development tools the ability to search Google's official developer documentation and retrieve...": "Google 开发者知识 MCP 服务器赋予 AI 驱动的开发工具搜索 Google 官方报告和开发者文档并检索的能力...",
        "Google Kubernetes Engine (OSS)": "Google Kubernetes Engine (开源版)",
        "Enable Antigravity to interact with Google Kubernetes Engine (GKE).": "允许 Antigravity 与 Google Kubernetes Engine (GKE) 交互。",
        "Google Managed Service for Apache Kafka": "Google 托管式 Apache Kafka 服务",
        "Manage clusters for Managed Service for Apache Kafka and Kafka Connect using natural language.": "使用自然语言管理 Apache Kafka 托管服务和 Kafka Connect 的集群。",
        "Google Maps Platform Code Assist": "Google Maps 平台代码助手",
        "The Google Maps Platform Code Assist MCP server provides your favorite AI coding assistant with up-to-date, official Google Maps Platform documentation, code...": "Google Maps 平台代码助手 MCP 服务器为您喜爱的 AI 编码助手提供最新的官方 Google Maps 平台文档、代码...",
        "Hardware Acceleration": "硬件加速",
        "Harness": "Harness",
        "Harness MCP Server allows AI assistants to interact with the Harness platform APIs, enabling intelligent automation and assistance for software delivery and cloud...": "Harness MCP 服务器允许 AI 助手与 Harness 平台 API 进行交互，从而为软件交付和云提供智能自动化与协助...",
        "Heroku": "Heroku",
        "The Heroku Platform MCP Server enables seamless interaction with Heroku Platform resources, allowing LLMs to read, manage, and operate applications, add-ons,...": "Heroku 平台 MCP 服务器实现了与 Heroku 平台资源的无缝交互，允许大语言模型 (LLM) 读取、管理和运行应用程序、插件、...",
        "High": "高配/强力",
        "History": "历史对话",
        "Idle": "空闲中",
        "Indexing project files...": "正在为项目文件建立索引...",
        "Inherits from global settings. Local permissions have higher priority. Learn more.": "继承自全局设置。本地权限具有更高的优先级。了解更多。",
        "Installed MCP Servers": "已安装的 MCP 服务器",
        "Interact with Redis key-value stores": "与 Redis 键值存储交互",
        "Interact with your AlloyDB for PostgreSQL data using natural language. This MCP server allows you to securely connect to your database for executing SQL queries,...": "使用自然语言与您的 AlloyDB for PostgreSQL 数据进行交互。此 MCP 服务器允许您安全地连接到您的数据库以执行 SQL 查询...",
        "Interact with your BigQuery data using natural language. This MCP server allows you to securely connect to your datasets to search the datasets, inspect table...": "使用自然语言与您的 BigQuery 数据进行交互。此 MCP 服务器允许您安全地连接到您的数据集以搜索数据集、检查数据表...",
        "Interact with your Cloud SQL for PostgreSQL data using natural language. This MCP server allows you to securely connect to your database for executing SQL queries...": "使用自然语言与您的 Cloud SQL for PostgreSQL 数据进行交互。此 MCP 服务器允许您安全地连接到您的数据库以执行 SQL 查询...",
        "Interact with your Cloud SQL for SQL Server data using natural language. This MCP server allows you to securely connect to your database for executing SQL queries...": "使用自然语言与您的 Cloud SQL for SQL Server 数据进行交互。此 MCP 服务器允许您安全地连接到您的数据库以执行 SQL 查询...",
        "Interact with your Google Cloud Spanner data using natural language. This MCP server allows you to securely connect to your instances for executing SQL queries...": "使用自然语言与您的 Google Cloud Spanner 数据进行交互。此 MCP 服务器允许您安全地连接到您的实例以执行 SQL 查询...",
        "Interact with your Oracle Database data using natural language. This MCP server allows you to securely connect to your databases for executing SQL queries...": "使用自然语言与您的 Oracle 数据库数据交互。此 MCP 服务器允许您安全连接到数据库以执行 SQL 查询等。",
        "Keep Cloud": "以云端为准",
        "Keep In Menu Bar": "保持在菜单栏",
        "Keep Local": "以本地为准",
        "Keep running in background when closed": "关闭主窗口时保持后台挂起",
        "Keep your coding agent up to date with the latest web best practices.": "使您的代码智能体与最新的 Web 最佳实践保持同步。",
        "Knowledge Catalog": "知识目录",
        "Launch on startup": "开机自动启动",
        "Learn more.": "了解更多。",
        "Light": "浅色模式",
        "Light Theme": "浅色主题",
        "Linear": "Linear",
        "Official Linear.app MCP Server for interacting with Linear projects, issues, and workflows.": "用于与 Linear 项目、问题和工作流程交互的官方 Linear.app MCP 服务器。",
        "Local File System Operations": "本地文件系统操作权限",
        "Local Permissions": "本地权限",
        "Locofy": "Locofy",
        "The Locofy MCP Server enables Locofy.ai code to be integrated and extended with your IDE.": "Locofy MCP 服务器使 Locofy.ai 代码能够与您的 IDE 集成和扩展。",
        "Logs": "运行日志面板",
        "Looker": "Looker",
        "Connect your AI assistants to Looker business intelligence. This MCP server enables data exploration and content management by allowing you to execute natural...": "将您的 AI 助手连接到 Looker 商业智能。此 MCP 服务器允许您执行自然语言交互，从而实现数据探索和内容管理...",
        "Low": "低配/本地",
        "MCP Toolbox for Databases": "数据库 MCP 工具箱",
        "The MCP Toolbox for Databases is an open-source MCP server designed to simplify and secure the development of tools for interacting with databases.": "数据库 MCP 工具箱是一个开源 MCP 服务器，旨在简化和安全地开发与数据库交互的工具。",
        "MCP Tools": "MCP 工具",
        "Manage application settings.": "管理应用设置。",
        "Manage what features Antigravity can access.": "管理 Antigravity 允许访问的系统及文件特征。",
        "Manage your plan, credentials, and general preferences.": "管理您的订阅计划、凭证和通用首选项。",
        "Manage your stored conversation logs.": "管理您本地存储的 AI 对话日志。",
        "Marketing Emails": "接收营销邮件",
        "Max Tokens": "最大输出长度 (Max Tokens)",
        "Maximize": "最大化",
        "Medium": "均衡",
        "Minimize": "最小化",
        "Model": "模型",
        "Model Quota": "模型配额",
        "Models": "模型配置",
        "Modern Web Guidance": "现代 Web 指南",
        "MongoDB": "MongoDB",
        "A Model Context Protocol server for interacting with MongoDB Atlas.": "用于与 MongoDB Atlas 交互的模型上下文协议服务器。",
        "Neon": "Neon",
        "Neon MCP Server is an open-source tool that lets you interact with your Neon Postgres databases in natural language.": "Neon MCP Server 是一个开源工具，允许您使用自然语言与您的 Neon Postgres 数据库交互。",
        "Netlify": "Netlify",
        "Netlify MCP Server enables AI assistants to interact with Netlify's platform for managing sites, deployments, domains, and other web development workflows.": "Netlify MCP 服务器使 AI 助手能够与 Netlify 平台交互，管理站点、部署、域名和其他 Web 开发工作流。",
        "Network Access Rules": "网络访问规则",
        "Network Permissions": "网络权限",
        "New Conversation": "新建对话",
        "New Editor Window": "新建编辑器窗口",
        "No MCP Servers": "无 MCP 服务器",
        "No customizations found for this workspace.": "未找到此工作区的自定义内容。",
        "Not in Project": "非项目内",
        "Notification": "通知提示",
        "Notification Settings": "通知设置",
        "Notifications": "通知",
        "Notion": "Notion",
        "Official Notion MCP Server that allows interaction with Notion workspaces, pages, databases, and comments via the Notion API.": "官方 Notion MCP 服务器，允许通过 Notion API 与 Notion 工作区、页面、数据库和评论进行交互。",
        "Official Linearapp MCP Server for interacting with Linear projects, issues, and workflows.": "用于与 Linear 项目、问题和工作流交互的官方 Linearapp MCP 服务器。",
        "Official PayPal MCP Server that allows integration with PayPal APIs for payment processing, transaction management, and account operations.": "官方 PayPal MCP 服务器，允许与 PayPal API 集成以进行支付处理、交易管理和账户操作。",
        "Open": "打开",
        "Open Command Palette": "打开命令面板",
        "Open Conversation History": "打开历史对话日志",
        "Open Conversation Picker": "打开对话选择器",
        "Open Keyboard Shortcuts": "打开快捷键设置面板",
        "Open Launchpad": "打开启动台",
        "Open Project Picker": "打开项目选择器",
        "Open Settings": "打开设置",
        "Open System Preferences": "打开系统偏好设置",
        "Oracle Database": "Oracle 数据库",
        "Outside of folders file access policy": "文件夹外部文件访问策略",
        "Parallel Tool Execution": "允许并行工具执行",
        "PayPal": "PayPal",
        "Permanently delete all conversation history. This cannot be undone.": "永久删除所有会话记录。此操作不可逆，请谨慎操作。",
        "Perplexity Ask": "Perplexity 提问",
        "An MCP server implementation that integrates the Perplexity Sonar API to provide real-time, web-wide research capabilities.": "一个集成了 Perplexity Sonar API 的 MCP 服务器实现，用以提供实时、全网范围的研究能力。",
        "Permissions": "权限",
        "Pinecone": "Pinecone",
        "The Pinecone MCP Server enables AI tools to search Pinecone documentation, configure indexes, generate code informed by your index configuration, and...": "Pinecone MCP 服务器使 AI 工具能够搜索 Pinecone 文档、配置索引、根据您的索引配置生成代码、以及...",
        "Plugins are packaged collections of skills and MCPs to help the Agent in Antigravity work with Google developer products. You can always change your choices in Settings.": "插件是技能和 MCP 的打包集合，帮助 Antigravity 中的智能体与 Google 开发者产品协同工作。您随时可以在设置中更改您的选择。",
        "Postman": "Postman",
        "The Postman MCP Server connects Postman to AI tools, giving AI agents and assistants the ability to access workspaces, manage collections and environments,...": "Postman MCP 服务器将 Postman 连接到 AI 工具，使 AI 智能体和助手能够访问工作区、管理集合和环境、...",
        "Preset": "预设",
        "Prevent Sleep": "防止休眠",
        "Prevent the computer from sleeping while the app is running.": "在应用运行时防止计算机进入休眠状态。",
        "Prisma": "Prisma",
        "The Prisma MCP Server enables AI tools to interact with Prisma for creating and managing Postgres databases easily.": "Prisma MCP 服务器使 AI 工具能够与 Prisma 交互，轻松创建和管理 Postgres 数据库。",
        "Projects": "项目列表",
        "Prompt on Write": "写入时弹窗提示",
        "Prompt tokens": "输入（提示词）Token",
        "Prototype, build & run modern apps users love with Firebase's backend, AI, and operational infrastructure.": "利用 Firebase 的后端、AI 和运营基础设施，原型设计、构建和运行用户喜爱的现代应用。",
        "Provide Feedback": "提供反馈",
        "Provide feedback": "提供反馈",
        "Proxy": "网络代理配置",
        "Receive product updates, tips, and promotions from Google Antigravity via email.": "通过邮件接收来自 Google Antigravity 的产品更新、提示和促销信息。",
        "Redis": "Redis",
        "Refresh": "刷新",
        "Refreshes in 6 days, 23 hours": "将在 6 天 23 小时后重置",
        "Reliable automation, in-depth debugging, and performance analysis in Chrome using Chrome DevTools and Puppeteer": "使用 Chrome DevTools 和 Puppeteer 在 Chrome 中进行可靠的自动化、深度调试和性能分析。",
        "Remove": "移除",
        "Request Review": "请求审核",
        "Require Review": "需要审核",
        "Require confirmation before running commands": "运行终端命令前需要人工确认",
        "Requires manual review for all terminal commands and file accesses outside of the working folder.": "要求对所有终端命令和工作文件夹外部的文件访问进行手动审核。",
        "Reset Zoom": "重置缩放",
        "Sandbox Only": "仅限沙箱环境",
        "Scheduled Tasks": "计划任务",
        "Science": "科学",
        "Search MCP servers by name": "按名称搜索 MCP 服务器",
        "Search your Google Cloud projects using natural language.": "使用自然语言搜索您的 Google Cloud 项目。",
        "Security Preset": "安全预设",
        "Select Project": "选择项目",
        "Select folder(s)": "选择文件夹",
        "Select light, dark, or inherit system settings.": "选择浅色、深色或跟随系统设置。",
        "Select Next Conversation": "选择下一个对话",
        "Select Previous Conversation": "选择上一个对话",
        "Send message": "发送消息",
        "Sequential Thinking": "顺序思考",
        "Settings": "设置",
        "Shortcut": "快捷键组合",
        "Shortcuts": "快捷键",
        "Sign Out": "退出登录",
        "Skip": "跳过",
        "Slide Window": "滑动窗口机制",
        "SonarQube": "SonarQube",
        "SonarQube MCP Server enables AI assistants to interact with SonarQube instances for code quality analysis, project management, and quality gate operations.": "SonarQube MCP 服务器使 AI 助手能够与 SonarQube 实例交互，进行代码质量分析、项目管理和质量门禁操作。",
        "Sonatype Guide": "Sonatype 指南",
        "Sonatype MCP server for interacting with our dependency management and security intelligence platform.": "用于与我们的依赖管理和安全情报平台交互的 Sonatype MCP 服务器。",
        "Spanner": "Spanner",
        "Interact with your Google Cloud Spanner data using natural language. This MCP server allows you to securely connect to your instances for executing SQL queries,...": "使用自然语言与您的 Google Cloud Spanner 数据进行交互。此 MCP 服务器允许您安全地连接到您的实例以执行 SQL 查询...",
        "Specifies Agent's behavior when asking for review on artifacts, which are documents it creates to enable a richer conversation experience.": "指定智能体在请求审核其创建的产物（文档）时的行为，以实现更丰富的对话体验。",
        "Startup": "启动项设置",
        "Stitch": "Stitch",
        "The Stitch MCP server enables AI assistants to interact with Stitch for vibe design: generating UI designs from text and images, and accessing project and screen...": "Stitch MCP 服务器使 AI 助手能够与 Stitch 进行交互以进行氛围设计：从文本和图像生成 UI 设计，以及访问项目和屏幕...",
        "Stop generating": "停止生成",
        "Strict": "严格限制",
        "Stripe": "Stripe",
        "The Stripe Model Context Protocol server allows you to integrate with Stripe APIs through function calling. This protocol supports various tools to interact with...": "Stripe 模型上下文协议服务器允许您通过函数调用与 Stripe API 进行集成。该协议支持各种与 Stripe 交互的工具...",
        "Structured Thinking": "顺序思考",
        "A Model Context Protocol server that provides structured thinking and reasoning capabilities for LLM conversations.": "一个为 LLM 对话提供结构化思考和推理能力的模型上下文协议服务器。",
        "Summarize Oldest": "自动总结旧会话",
        "Supabase": "Supabase",
        "Connect your Supabase projects to AI assistants. This MCP server allows managing tables, fetching config, executing SQL queries, managing edge functions, and...": "将您的 Supabase 项目连接到 AI 助手。此 MCP 服务器允许管理数据表、获取配置、执行 SQL 查询、管理边缘函数等...",
        "Sync Conflicts Resolution": "同步冲突解决方法",
        "System": "跟随系统",
        "System Integration": "系统级深度集成",
        "System Prompt": "系统提示词 (System Prompt)",
        "System Proxy": "跟随系统代理",
        "Tasks": "计划任务",
        "Telemetry": "遥测",
        "Temperature": "温度 / 随机性 (Temperature)",
        "Terminal": "终端控制",
        "Terminal & Tooling Permissions": "终端与工具权限",
        "Terminal Command Auto Execution": "终端命令自动执行",
        "Terminal Commands": "终端命令",
        "Terminal view": "切换终端视图",
        "The Bigtable Admin remote MCP server lets you manage Bigtable resources.": "Bigtable Admin 远程 MCP 服务器让您可以管理 Bigtable 资源。",
        "The ClickHouse MCP server enables agents to securely interact with ClickHouse databases. It provides a universal interface to execute SQL, explore data, and view...": "ClickHouse MCP 服务器使智能体能够安全地与 ClickHouse 数据库交互。它提供了执行 SQL、探索数据和查看...的统一接口。",
        "The Cloud SQL remote MCP server lets you access and run Cloud SQL tools to create, manage, and query Cloud SQL resources from your AI-enabled developme...": "Cloud SQL 远程 MCP 服务器允许您从启用 AI 的开发环境中访问并运行 Cloud SQL 工具，以创建、管理和查询 Cloud SQL 资源。",
        "The Dart and Flutter MCP server exposes Dart (and Flutter) development tool actions to compatible AI-assistant clients.": "Dart 和 Flutter MCP 服务器向兼容的 AI 助手客户端暴露 Dart（和 Flutter）开发工具操作。",
        "The Dev Mode MCP Server brings Figma directly into your workflow by providing important design information and context to AI agents generating code from Fig...": "开发模式 MCP 服务器通过将重要的设计信息和上下文提供给从 Figma 生成代码的 AI 智能体，将 Figma 直接带入您的工作流。",
        "The Firebase Model Context Protocol (MCP) Server gives AI-powered development tools the ability to work with your Firebase projects and your app's codebase.": "Firebase 模型上下文协议 (MCP) 服务器使 AI 驱动的开发工具能够操作您的 Firebase 项目和应用的代码库。",
        "The Genkit Model Context Protocol (MCP) Server gives AI-powered development tools the ability to build, debug and inspect your Genkit app.": "Genkit 模型上下文协议 (MCP) 服务器使 AI 驱动的开发工具能够构建、调试和检查您的 Genkit 应用。",
        "The GitHub MCP Server is a Model Context Protocol (MCP) server that provides seamless integration with GitHub APIs, enabling advanced automation and...": "GitHub MCP 服务器是一个模型上下文协议 (MCP) 服务器，提供与 GitHub API 的无缝集成，实现高级自动化和...",
        "The Google Developer Knowledge MCP server gives AI-powered development tools the ability to search Google's official developer documentation and retrieve...": "Google 开发者知识 MCP 服务器使 AI 驱动的开发工具能够搜索 Google 的官方开发者文档并检索...",
        "The Google Maps Platform Code Assist MCP server provides your favorite AI coding assistant with up-to-date, official Google Maps Platform documentation, code...": "Google Maps Platform Code Assist MCP 服务器为您喜爱的 AI 编程助手提供最新的、官方的 Google Maps 平台文档、代码...",
        "The Heroku Platform MCP Server enables seamless interaction with Heroku Platform resources, allowing LLMs to read, manage, and operate applications, add-ons...": "Heroku 平台 MCP 服务器允许与 Heroku 平台资源无缝交互，允许 LLM 读取、管理和操作应用、附加组件等。",
        "The Locofy MCP Server enables Locofy.ai code to be integrated and extended with your IDE.": "Locofy MCP 服务器使 Locofy.ai 代码能够与您的 IDE 集成和扩展。",
        "The MCP Toolbox for Databases is an open-source MCP server designed to simplify and secure the development of tools for interacting with databases.": "数据库 MCP 工具箱是一个开源 MCP 服务器，旨在简化和安全地开发与数据库交互的工具。",
        "The Pinecone MCP Server enables AI tools to search Pinecone documentation, configure indexes, generate code informed by your index configuration, and...": "Pinecone MCP 服务器使 AI 工具能够搜索 Pinecone 文档、配置索引、根据您的索引配置生成代码等。",
        "The Postman MCP Server connects Postman to AI tools, giving AI agents and assistants the ability to access workspaces, manage collections and environments...": "Postman MCP 服务器将 Postman 连接到 AI 工具，赋予 AI 智能体和助手访问工作区、管理集和环境的能力...",
        "The Prisma MCP Server enables AI tools to interact with Prisma for creating and managing Postgres databases easily.": "Prisma MCP 服务器使 AI 工具能够与 Prisma 交互，轻松创建和管理 Postgres 数据库。",
        "The Stitch MCP server enables AI assistants to interact with Stitch for vibe design: generating UI designs from text and images, and accessing project and screen...": "Stitch MCP 服务器使 AI 助手能够与 Stitch 交互以进行氛围设计：从文本和图像生成 UI 设计，并访问项目和屏幕...",
        "The Stripe Model Context Protocol server allows you to integrate with Stripe APIs through function calling. This protocol supports various tools to interact with...": "Stripe 模型上下文协议服务器允许您通过函数调用与 Stripe API 集成。该协议支持各种工具以交互...",
        "The app will be accessible from the menu bar and will keep running in the background when all windows are closed.": "该应用将可从菜单栏访问，并且当所有窗口关闭时将在后台保持运行。",
        "The breakdown below shows token usage from customizations like skills, rules, and MCP. If the budget is exceeded, large customizations will be truncated automatically.": "下方列表显示了技能、规则和 MCP 等自定义内容所消耗的 Token 用量。如果超过配额，大型自定义内容将被自动截断。",
        "Theme": "外观主题",
        "Thinking": "深度思考",
        "Thinking...": "深度思考中...",
        "This MCP server provides your LLM with docs and examples to instrument your AI apps with Arize AI. It also provides access to Arize support. Connect it to your IDE...": "此 MCP 服务器为您的 LLM 提供文档和示例，以便使用 Arize AI 来监测您的 AI 应用。它还提供对 Arize 支持的访问。将其连接到您的 IDE...",
        "To modify notification settings, open your operating system's system preferences.": "要修改通知设置，请打开您操作系统的系统偏好设置。",
        "Toggle Auxiliary Pane": "切换辅助面板",
        "Toggle Developer Tools": "切换开发者工具",
        "Toggle Model Selector": "切换模型选择器",
        "Toggle Project Selector": "切换项目选择器",
        "Toggle Sidebar": "切换侧边栏",
        "Toggle Voice Recording": "切换语音录制/输入",
        "Token Usage": "Token 使用量",
        "Token Usage Tracker": "Token 消耗统计追踪",
        "Tool Calls History": "工具调用历史链",
        "Tool Discovery Path": "工具自动检测路径",
        "Top P": "核采样 (Top P)",
        "Total tokens": "总计消耗 Token",
        "Unrestricted": "完全信任/无限制",
        "Use WSL/Docker Backend If Available": "优先使用 WSL/Docker 后台环境",
        "Use hardware acceleration when available.": "在可用时开启显卡硬件加速（提升渲染流利度）。",
        "User Input Analysis": "用户意图结构化分析",
        "Using the Antigravity Python SDK to build AI agents": "使用 Antigravity Python SDK 构建 AI 智能体。",
        "Verbose agent chat": "详细输出的智能体聊天",
        "Version 2.0.1": "版本 2.0.1",
        "Vertex AI Search": "Vertex AI Search",
        "Perform searches on ingested data in Google-owned data stores.": "对导入到 Google 旗下数据存储中的数据执行搜索。",
        "View": "视图",
        "View Code Diff": "查看代码前后对比（Diff）",
        "View your available model quota. Quota refreshes periodically based on your plan.": "查看您可用的模型配额。配额会根据您的订阅计划定期重置。",
        "Voice input": "语音输入",
        "Web Search & Retrieval": "网络搜索与实时信息检索",
        "When toggled on, Antigravity collects usage data to help Google enhance performance and features.": "开启后，Antigravity 将收集匿名使用数据以帮助谷歌优化性能和功能。",
        "Window": "窗口",
        "Workspace Context": "工作区上下文关联",
        "Zoom In": "放大",
        "Zoom Out": "缩小"
    };

    function translate() {
        document.querySelectorAll('*').forEach(el => {
            if (el.childNodes.length) {
                el.childNodes.forEach(node => {
                    if (node.nodeType === Node.TEXT_NODE) {
                        const trimmed = node.nodeValue.trim();
                        if (i18nMap[trimmed]) {
                            node.nodeValue = node.nodeValue.replace(trimmed, i18nMap[trimmed]);
                        }
                    }
                });
            }
        });
    }

    // 立即执行一次
    translate();
    // 监听界面变化（防止AI聊天刷新后变回英文）
    const observer = new MutationObserver(translate);
    observer.observe(document.body, { childList: true, subtree: true });
    console.log('--- Antigravity 动态汉化补丁注入成功！---');
})();