# 密码
requirepass 自己写个强密码
# 开启AOF持久化功能
appendonly yes
# 用于指定AOF数据的同步频率，即操作系统将内存中的数据刷写到磁盘的策略。设置为everysec表示每秒钟执行一次同步操作，将这1秒内积累的写命令刷入磁盘。这是一种折中的策略，它在性能和数据安全之间取得了平衡：即使发生系统崩溃，最多也只会丢失1秒钟的数据1。
appendfsync everysec
# 将数据库设置为1个，也就是数据库默认编号为0
databases 1
# 为了在生产环境彻底杜绝误切，额外添加命令重命名，禁用 SELECT 命令
rename-command SELECT ""