systemLog:
  destination: file
  path: /export/servers/standalone/log/mongodb.log
  logAppend: true
net:
  bindIp: nosql01
  port: 27016
storage:
  dbPath: /export/servers/standalone/dbs
processManagement:
  fork: true
