@Entry
@Component
struct PropertyAnimate2 {
  @State widthSize: number = 250
  @State heightSize: number = 100
  @State rotateAngle: number = 0
  @State flag: boolean = true
  build() {
    Column() {
      Button('change size')
        .onClick(() => {
          if (this.flag) {
            this.widthSize = 150
            this.heightSize = 60
          } else {
            this.widthSize = 250
            this.heightSize = 100
          }
          this.flag = !this.flag
        })
        .margin(30)
        .width(this.widthSize)
        .height(this.heightSize)
        .animation({
          duration: 2000, curve: Curve.EaseOut, iterations: 3, playMode: PlayMode.Normal
        })
      Button('change rotate angle')
        .onClick(() => {
          this.rotateAngle = 90
        })
        .margin(50)
        .rotate({ angle: this.rotateAngle })
        .animation({
          duration: 1200, curve: Curve.Friction, delay: 500, iterations: -1, // 设置-1 表示动画无限循环
          playMode: PlayMode.Alternate, expectedFrameRateRange: {
            min: 20, max: 120, expected: 90, }
        })
    }.width('100%').margin({ top: 20 })
  }
}