services:
  cvat_ui:
    labels:
      # 其余所有根路径请求发往前端 UI
      traefik.http.routers.cvat-ui.rule: PathPrefix(`/`)
  cvat_db:
    # 数据库持久化
    volumes:
      - ../CVAT_DATA/cvat_db:/var/lib/postgresql/data
  cvat_redis_inmem:
    volumes:
      - ../CVAT_DATA/cvat_inmem_db:/data
  cvat_redis_ondisk:
    volumes:
      - ../CVAT_DATA/cvat_cache_db:/var/lib/kvrocks
      # 你需要确保 kvrocks.conf 文件存在于改目录下（写入内容）
      # bind 0.0.0.0
      # port 6666
      # daemonize no
      # logfile stdout
      # dir /var/lib/kvrocks/data
  cvat_server:
    volumes:
      # 共享目录(读取权限)
      - ../CVAT_DATA/cvat_share:/home/django/share:ro
      # 核心后端数据
      - ../CVAT_DATA/cvat_data:/home/django/data  # 用户上传的任务数据
      - ../CVAT_DATA/cvat_keys:/home/django/keys  # 密钥
      - ../CVAT_DATA/cvat_logs:/home/django/logs  # 日志
    environment:
      DJANGO_EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
      DJANGO_EMAIL_HOST: smtp.qq.com
      DJANGO_EMAIL_PORT: 587
      DJANGO_EMAIL_HOST_USER: fsdfsddfsf@qq.com
      DJANGO_EMAIL_HOST_PASSWORD: fsdfsdfdsfsdf
      DJANGO_EMAIL_USE_TLS: "true"
      DJANGO_DEFAULT_FROM_EMAIL: fsdfsdfsdfsdfsd@qq.com
      # 这一步是放开 Django 的限制
      ALLOWED_HOSTS: "*"
    labels:
      # 精准拦截 API 和后端相关路径发往 Server
      traefik.http.routers.cvat.rule: PathPrefix(`/api/`) || PathPrefix(`/static/`) || PathPrefix(`/admin`) || PathPrefix(`/django-rq`)

  cvat_worker_utils:
    volumes:
      # 共享目录(读取权限)
      - ../CVAT_DATA/cvat_share:/home/django/share:ro
      # 核心后端数据
      - ../CVAT_DATA/cvat_data:/home/django/data  # 用户上传的任务数据
      - ../CVAT_DATA/cvat_keys:/home/django/keys  # 密钥
      - ../CVAT_DATA/cvat_logs:/home/django/logs  # 日志

  cvat_worker_import:
    volumes:
      # 共享目录(读取权限)
      - ../CVAT_DATA/cvat_share:/home/django/share:ro
      # 核心后端数据
      - ../CVAT_DATA/cvat_data:/home/django/data  # 用户上传的任务数据
      - ../CVAT_DATA/cvat_keys:/home/django/keys  # 密钥
      - ../CVAT_DATA/cvat_logs:/home/django/logs  # 日志

  cvat_worker_export:
    volumes:
      # 共享目录(读取权限)
      - ../CVAT_DATA/cvat_share:/home/django/share:ro
      # 核心后端数据
      - ../CVAT_DATA/cvat_data:/home/django/data  # 用户上传的任务数据
      - ../CVAT_DATA/cvat_keys:/home/django/keys  # 密钥
      - ../CVAT_DATA/cvat_logs:/home/django/logs  # 日志

  cvat_worker_annotation:
    volumes:
      # 共享目录(读取权限)
      - ../CVAT_DATA/cvat_share:/home/django/share:ro
      # 核心后端数据
      - ../CVAT_DATA/cvat_data:/home/django/data  # 用户上传的任务数据
      - ../CVAT_DATA/cvat_keys:/home/django/keys  # 密钥
      - ../CVAT_DATA/cvat_logs:/home/django/logs  # 日志

  cvat_worker_webhooks:
    volumes:
      # 共享目录(读取权限)
      - ../CVAT_DATA/cvat_share:/home/django/share:ro
      # 核心后端数据
      - ../CVAT_DATA/cvat_data:/home/django/data  # 用户上传的任务数据
      - ../CVAT_DATA/cvat_keys:/home/django/keys  # 密钥
      - ../CVAT_DATA/cvat_logs:/home/django/logs  # 日志

  cvat_worker_quality_reports:
    volumes:
      # 共享目录(读取权限)
      - ../CVAT_DATA/cvat_share:/home/django/share:ro
      # 核心后端数据
      - ../CVAT_DATA/cvat_data:/home/django/data  # 用户上传的任务数据
      - ../CVAT_DATA/cvat_keys:/home/django/keys  # 密钥
      - ../CVAT_DATA/cvat_logs:/home/django/logs  # 日志

  cvat_worker_chunks:
    volumes:
      # 共享目录(读取权限)
      - ../CVAT_DATA/cvat_share:/home/django/share:ro
      # 核心后端数据
      - ../CVAT_DATA/cvat_data:/home/django/data  # 用户上传的任务数据
      - ../CVAT_DATA/cvat_keys:/home/django/keys  # 密钥
      - ../CVAT_DATA/cvat_logs:/home/django/logs  # 日志

  cvat_worker_consensus:
    volumes:
      # 共享目录(读取权限)
      - ../CVAT_DATA/cvat_share:/home/django/share:ro
      # 核心后端数据
      - ../CVAT_DATA/cvat_data:/home/django/data  # 用户上传的任务数据
      - ../CVAT_DATA/cvat_keys:/home/django/keys  # 密钥
      - ../CVAT_DATA/cvat_logs:/home/django/logs  # 日志

  # # 启动错误就直接禁用这个服务算了，说我yaml文件路径有问题，那确实是一个文件呀
  # cvat_vector:
  #   profiles: ["disabled"]

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /mnt/share
      o: bind
