spring.application.name=my
server.port=8080

# MySQL???????
spring.datasource.url=jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=yandifei

# ??????????
mybatis.configuration.map-underscore-to-camel-case=true

# ??MyBatis?XML??????
mybatis.mapper-locations=classpath:mapper/*.xml
# ??XML???????????????,??????????????
mybatis.type-aliases-package=com.my.domain,com.my.pojo

# ??????(??????????)
mybatis.configuration.auto-mapping-behavior=full
# ???????????????
mybatis.configuration.cache-enabled=true
# ?????SQL??
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl