storage:
  dbPath: .\data\config2
systemLog:
  destination: file
  path: .\logs\config2\mongod.log
  logAppend: true
net:
  bindIp: 0.0.0.0
  port: 27020
replication:
  replSetName: configRepl
sharding:
  clusterRole: configsvr
