storage:
  dbPath: .\data\config1
systemLog:
  destination: file
  path: .\logs\config1\mongod.log
  logAppend: true
net:
  bindIp: 0.0.0.0
  port: 27019
replication:
  replSetName: configRepl
sharding:
  clusterRole: configsvr
