systemLog:
  destination: file
  path: .\logs\mongos\mongos.log
  logAppend: true
net:
  bindIp: 0.0.0.0
  port: 27018
sharding:
  configDB: configRepl/localhost:27019,localhost:27020,localhost:27021,localhost:27022
