storage:
  dbPath: .\data\shard24
systemLog:
  destination: file
  path: .\logs\shard24\mongod.log
  logAppend: true
net:
  bindIp: 0.0.0.0
  port: 47020
replication:
  replSetName: shard2
sharding:
  clusterRole: shardsvr
