storage:
  dbPath: .\data\shard13
systemLog:
  destination: file
  path: .\logs\shard13\mongod.log
  logAppend: true
net:
  bindIp: 0.0.0.0
  port: 37019
replication:
  replSetName: shard1
sharding:
  clusterRole: shardsvr
