storage:
  dbPath: .\data\shard21
systemLog:
  destination: file
  path: .\logs\shard21\mongod.log
  logAppend: true
net:
  bindIp: 0.0.0.0
  port: 47017
replication:
  replSetName: shard2
sharding:
  clusterRole: shardsvr
