storage:
  dbPath: .\data\shard12
systemLog:
  destination: file
  path: .\logs\shard12\mongod.log
  logAppend: true
net:
  bindIp: 0.0.0.0
  port: 37018
replication:
  replSetName: shard1
sharding:
  clusterRole: shardsvr
