storage:
  dbPath: .\data\shard11
systemLog:
  destination: file
  path: .\logs\shard11\mongod.log
  logAppend: true
net:
  bindIp: 0.0.0.0
  port: 37017
replication:
  replSetName: shard1
sharding:
  clusterRole: shardsvr
